<body>
<div class="contenairselect">
<div id="LieneConnexion" class="selection1" ondblclick="changePage('index.php?view=connexion')">
    <h2 class="titreselec">Se connecter</h2>
</div>
<div id="LienInscription" class="selection2">
    <h2 class="titreselec" >Sincrire</h2>
</div>
</div>
<div id="présentation">
<h2>Qu'est-ce que Circuit-Training ?</h2>
<p> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Laoreet sit amet cursus sit amet dictum sit amet. Venenatis tellus in metus vulputate. In eu mi bibendum neque egestas. Pharetra sit amet aliquam id diam. Risus nec feugiat in fermentum posuere urna nec tincidunt praesent. Vel fringilla est ullamcorper eget nulla facilisi. Rhoncus urna neque viverra justo nec ultrices dui sapien eget. Viverra maecenas accumsan lacus vel facilisis volutpat. Elit at imperdiet dui accumsan sit amet. Elementum nibh tellus molestie nunc non blandit massa enim nec.
Tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras fermentum. Sit amet nisl suscipit adipiscing bibendum. Etiam tempor orci eu lobortis elementum nibh. Orci phasellus egestas tellus rutrum tellus pellentesque eu tincidunt. Lectus quam id leo in vitae turpis. Convallis aenean et tortor at. Maecenas sed enim ut sem viverra aliquet eget sit. Nisl condimentum id venenatis a condimentum vitae. At ultrices mi tempus imperdiet nulla malesuada pellentesque elit. Porta nibh venenatis cras sed felis eget velit aliquet. Tincidunt ornare massa eget egestas purus viverra accumsan.
Id velit ut tortor pretium viverra suspendisse. Eget arcu dictum varius duis. Morbi tristique senectus et netus et malesuada fames ac. Id aliquet risus feugiat in ante metus dictum at. Amet risus nullam eget felis eget nunc lobortis mattis. Nulla porttitor massa id neque aliquam vestibulum. Vivamus at augue eget arcu dictum. Mauris augue neque gravida in. Lobortis elementum nibh tellus molestie. Vitae suscipit tellus mauris a diam. Sit amet commodo nulla facilisi nullam vehicula ipsum a. Viverra orci sagittis eu volutpat odio. Non sodales neque sodales ut etiam sit amet. Habitant morbi tristique senectus et netus et malesuada. Tristique sollicitudin nibh sit amet commodo nulla facilisi nullam. Varius vel pharetra vel turpis nunc eget lorem dolor sed. In tellus integer feugiat scelerisque varius morbi enim nunc faucibus.
Aenean et tortor at risus viverra adipiscing at in. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada proin. At augue eget arcu dictum varius. Eget nullam non nisi est sit. Libero nunc consequat interdum varius sit amet mattis vulputate enim. Nisi quis eleifend quam adipiscing vitae proin sagittis. Quam adipiscing vitae proin sagittis nisl rhoncus mattis. Et malesuada fames ac turpis egestas. Iaculis urna id volutpat lacus laoreet. Ultrices gravida dictum fusce ut placerat orci nulla pellentesque. Dui nunc mattis enim ut. Proin sagittis nisl rhoncus mattis rhoncus urna neque. Imperdiet sed euismod nisi porta lorem. Rhoncus dolor purus non enim praesent elementum. Urna nec tincidunt praesent semper feugiat nibh sed pulvinar proin.
Viverra justo nec ultrices dui sapien eget mi proin. Ipsum faucibus vitae aliquet nec ullamcorper sit. Tristique nulla aliquet enim tortor at auctor urna. Lacinia at quis risus sed vulputate odio ut enim blandit. Condimentum id venenatis a condimentum vitae sapien pellentesque habitant morbi. Interdum velit laoreet id donec ultrices tincidunt arcu non. Mauris sit amet massa vitae tortor condimentum lacinia. Velit euismod in pellentesque massa placerat. Iaculis at erat pellentesque adipiscing commodo elit. Ac feugiat sed lectus vestibulum mattis ullamcorper velit. Massa placerat duis ultricies lacus sed turpis tincidunt id aliquet. Id neque aliquam vestibulum morbi blandit. Lacus laoreet non curabitur gravida arcu ac. Augue neque gravida in fermentum. Ultrices tincidunt arcu non sodales neque sodales ut..</p>
</div>   
</body>

